services:
  be-vita-hot-engine:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: be-vita-hot-engine
    env_file:
      - ../.env.production
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port $${APP_PORT:-8000}"
